apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kuberstore
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 0.0.0.0
    path: "/kuberstore"