---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: anaconda3-opencv-ssh-pubkey
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: anaconda3-opencv-ssh-pubkey
    spec:
      containers:
      - name: anaconda3-opencv-ssh-pubkey
        image: noboevbo/anaconda3-opencv-ssh-pubkey:latest
        lifecycle: #Workaround - defaultMode in secret seems buggy
          postStart:
            exec:
              command:
              - bash
              - -c
              - chmod 400 /root/.ssh
        command: ["/bin/bash"]
        args: ["-c", "/usr/sbin/sshd -D"]
        ports:
        - containerPort: 22
        volumeMounts:
        - name: nfs-kuberstore
          mountPath: /data
        - name: ssh-publickey
          mountPath: /root/.ssh

      volumes:
      - name: nfs-kuberstore
        persistentVolumeClaim:
          claimName: nfs-kuberstore
      - name: ssh-publickey
        secret: 
          secretName: ssh-authorized-keys-noboevbo-secret
          defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: anaconda3-opencv-ssh-pubkey-service
  labels:
    app: anaconda3-opencv-ssh-pubkey
spec:
  selector:
    app: anaconda3-opencv-ssh-pubkey
  ports:
  - port: 22
    protocol: TCP
    nodePort: 30002
  type: NodePort
---
