---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caffe-cuda-ssh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caffe-cuda-ssh
    spec:
      containers:
      - name: caffe-cuda-ssh
        image: noboevbo/caffe-cuda-ssh:latest
        ports:
        - containerPort: 22
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - name: nvidia-driver
          mountPath: /usr/local/nvidia
        - name: nfs-kuberstore
          mountPath: /data

      volumes:
      - name: nvidia-driver
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.82
      - name: nfs-kuberstore
        persistentVolumeClaim:
          claimName: nfs-kuberstore
---
apiVersion: v1
kind: Service
metadata:
  name: caffe-cuda-ssh-service
  labels:
    app: caffe-cuda-ssh
spec:
  selector:
    app: caffe-cuda-ssh
  ports:
  - port: 22
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer
---
