---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caffe-cuda-ssh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caffe-cuda-ssh
    spec:
      containers:
      - name: caffe-cuda-ssh
        image: noboevbo/caffe-cuda-ssh-pubkey:latest
        lifecycle: #Workaround - defaultMode in secret seems buggy
          postStart:
            exec:
              command:
              - bash
              - -c
              - chmod 400 /root/.ssh
        command: ["/bin/bash"]
        args: ["-c", "/usr/sbin/sshd -D"]
        ports:
        - containerPort: 22
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - name: nvidia-driver
          mountPath: /usr/local/nvidia
        - name: nfs-kuberstore
          mountPath: /data
        - name: ssh-publickey
          mountPath: /root/.ssh

      volumes:
      - name: nvidia-driver
        hostPath:
          path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.82
      - name: nfs-kuberstore
        persistentVolumeClaim:
          claimName: nfs-kuberstore
      - name: ssh-publickey
        secret: 
          secretName: ssh-authorized-keys-noboevbo-secret
          defaultMode: 0400
---
apiVersion: v1
kind: Service
metadata:
  name: caffe-cuda-ssh-service
  labels:
    app: caffe-cuda-ssh
spec:
  selector:
    app: caffe-cuda-ssh
  ports:
  - port: 22
    protocol: TCP
    nodePort: 30001
  type: NodePort
---
